// Auto-generated by ph-curves-gen. Do not edit.

use ph_curves::MonotonicCurveLut;

use ph_curves::{BoundaryBehavior, MonotonicDirection, ObservationGuardBehavior, ObservationGuardMetadata, PiecewiseLinearTransfer, TransferMetadata};

type MonoLut = MonotonicCurveLut<u8, u8, 256>;

static LINEAR_FWD: [u8; 256] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255];
static LINEAR_INV: [u8; 256] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255];
/// "linear" — monotonic curve.
pub const LINEAR: MonoLut = MonoLut::new(&LINEAR_FWD, &LINEAR_INV);

#[rustfmt::skip]
static FRONT_END_HIGH_DC_INPUTS: [u16; 2] = [100, 250];
#[rustfmt::skip]
static FRONT_END_HIGH_DC_OUTPUTS: [i32; 2] = [3201, 8006];
/// Family: "front\_end".
/// Selectors: "coupling" = "dc", "range" = "high".
/// "front\_end\_high\_dc" sparse physical transfer function.
///
/// Source provenance: identity "synthetic multi-range ADC note"; locator "Table 1".
/// Representation: "scaled polynomial (3 coefficients, scale=32000/1000000)".
/// Generation policy: requested interpolation error <= 1; max_knots = 32; below = error; above = clamp.
/// Domain: 100..=250 "adc\_code"; output: "millivolt" x 1000.
/// Knots: 2 (12 bytes array payload).
/// Exhaustive numerical error: requested <= 1, achieved 0.864000 output quanta
/// (conservative metadata bound 1) at input 175.
/// This is table/quantization error against the configured ideal source, not total sensor accuracy.
/// Observation guard: code 65535 with Error behavior.
/// Classification of this code as saturation is cited from identity "synthetic multi-range ADC note"; locator "§4 saturation" and applied as declared policy, not inferred from the integer value.
#[rustfmt::skip]
pub const FRONT_END_HIGH_DC: PiecewiseLinearTransfer<2> =
PiecewiseLinearTransfer::new(&FRONT_END_HIGH_DC_INPUTS, &FRONT_END_HIGH_DC_OUTPUTS, MonotonicDirection::Increasing)
.with_boundaries(BoundaryBehavior::Error, BoundaryBehavior::Clamp)
.with_observation_guard(65535, ObservationGuardBehavior::Error);
/// Metadata for [`FRONT_END_HIGH_DC`].
pub const FRONT_END_HIGH_DC_METADATA: TransferMetadata = TransferMetadata {
    input_unit: "adc_code",
    output_unit: "millivolt",
    output_scale: 1000,
    domain_min: 100,
    domain_max: 250,
    range_min: 3201,
    range_max: 8006,
    direction: MonotonicDirection::Increasing,
    knot_count: 2,
    strictly_monotonic: true,
    flat_segment_count: 0,
    requested_max_error: 1,
    achieved_max_error: 1,
    worst_case_input: 175,
    achieved_max_inverse_code_error: 0,
};
/// Optional observation-code guard for [`FRONT_END_HIGH_DC`].
///
/// Classification of a code as saturation is cited from identity "synthetic multi-range ADC note"; locator "§4 saturation" and applied as declared policy,
/// not inferred from the integer value. The runtime getter and this constant agree.
pub const FRONT_END_HIGH_DC_OBSERVATION_GUARD: Option<ObservationGuardMetadata> = Some(ObservationGuardMetadata {
    code: 65535,
    behavior: ObservationGuardBehavior::Error,
});

#[rustfmt::skip]
static FRONT_END_LOW_DC_INPUTS: [u16; 2] = [100, 500];
#[rustfmt::skip]
static FRONT_END_LOW_DC_OUTPUTS: [i32; 2] = [200, 1000];
/// Family: "front\_end".
/// Selectors: "coupling" = "dc", "range" = "low".
/// "front\_end\_low\_dc" sparse physical transfer function.
///
/// Source provenance: identity "synthetic multi-range ADC note"; locator "Table 1".
/// Representation: "scaled polynomial (3 coefficients, scale=2000/1000000)".
/// Generation policy: requested interpolation error <= 1; max_knots = 32; below = error; above = clamp.
/// Domain: 100..=500 "adc\_code"; output: "millivolt" x 1000.
/// Knots: 2 (12 bytes array payload).
/// Exhaustive numerical error: requested <= 1, achieved 0.100000 output quanta
/// (conservative metadata bound 1) at input 500.
/// This is table/quantization error against the configured ideal source, not total sensor accuracy.
/// Observation guard: code 65535 with Error behavior.
/// Classification of this code as saturation is cited from identity "synthetic multi-range ADC note"; locator "§4 saturation" and applied as declared policy, not inferred from the integer value.
#[rustfmt::skip]
pub const FRONT_END_LOW_DC: PiecewiseLinearTransfer<2> =
PiecewiseLinearTransfer::new(&FRONT_END_LOW_DC_INPUTS, &FRONT_END_LOW_DC_OUTPUTS, MonotonicDirection::Increasing)
.with_boundaries(BoundaryBehavior::Error, BoundaryBehavior::Clamp)
.with_observation_guard(65535, ObservationGuardBehavior::Error);
/// Metadata for [`FRONT_END_LOW_DC`].
pub const FRONT_END_LOW_DC_METADATA: TransferMetadata = TransferMetadata {
    input_unit: "adc_code",
    output_unit: "millivolt",
    output_scale: 1000,
    domain_min: 100,
    domain_max: 500,
    range_min: 200,
    range_max: 1000,
    direction: MonotonicDirection::Increasing,
    knot_count: 2,
    strictly_monotonic: true,
    flat_segment_count: 0,
    requested_max_error: 1,
    achieved_max_error: 1,
    worst_case_input: 500,
    achieved_max_inverse_code_error: 0,
};
/// Optional observation-code guard for [`FRONT_END_LOW_DC`].
///
/// Classification of a code as saturation is cited from identity "synthetic multi-range ADC note"; locator "§4 saturation" and applied as declared policy,
/// not inferred from the integer value. The runtime getter and this constant agree.
pub const FRONT_END_LOW_DC_OBSERVATION_GUARD: Option<ObservationGuardMetadata> = Some(ObservationGuardMetadata {
    code: 65535,
    behavior: ObservationGuardBehavior::Error,
});

#[rustfmt::skip]
static FRONT_END_MID_DC_INPUTS: [u16; 2] = [100, 400];
#[rustfmt::skip]
static FRONT_END_MID_DC_OUTPUTS: [i32; 2] = [800, 3201];
/// Family: "front\_end".
/// Selectors: "coupling" = "dc", "range" = "mid".
/// "front\_end\_mid\_dc" sparse physical transfer function.
///
/// Source provenance: identity "synthetic multi-range ADC note"; locator "Table 1".
/// Representation: "scaled polynomial (3 coefficients, scale=8000/1000000)".
/// Generation policy: requested interpolation error <= 1; max_knots = 32; below = error; above = clamp.
/// Domain: 100..=400 "adc\_code"; output: "millivolt" x 1000.
/// Knots: 2 (12 bytes array payload).
/// Exhaustive numerical error: requested <= 1, achieved 0.600000 output quanta
/// (conservative metadata bound 1) at input 250.
/// This is table/quantization error against the configured ideal source, not total sensor accuracy.
/// Observation guard: code 65535 with Error behavior.
/// Classification of this code as saturation is cited from identity "synthetic multi-range ADC note"; locator "§4 saturation" and applied as declared policy, not inferred from the integer value.
#[rustfmt::skip]
pub const FRONT_END_MID_DC: PiecewiseLinearTransfer<2> =
PiecewiseLinearTransfer::new(&FRONT_END_MID_DC_INPUTS, &FRONT_END_MID_DC_OUTPUTS, MonotonicDirection::Increasing)
.with_boundaries(BoundaryBehavior::Error, BoundaryBehavior::Clamp)
.with_observation_guard(65535, ObservationGuardBehavior::Error);
/// Metadata for [`FRONT_END_MID_DC`].
pub const FRONT_END_MID_DC_METADATA: TransferMetadata = TransferMetadata {
    input_unit: "adc_code",
    output_unit: "millivolt",
    output_scale: 1000,
    domain_min: 100,
    domain_max: 400,
    range_min: 800,
    range_max: 3201,
    direction: MonotonicDirection::Increasing,
    knot_count: 2,
    strictly_monotonic: true,
    flat_segment_count: 0,
    requested_max_error: 1,
    achieved_max_error: 1,
    worst_case_input: 250,
    achieved_max_inverse_code_error: 0,
};
/// Optional observation-code guard for [`FRONT_END_MID_DC`].
///
/// Classification of a code as saturation is cited from identity "synthetic multi-range ADC note"; locator "§4 saturation" and applied as declared policy,
/// not inferred from the integer value. The runtime getter and this constant agree.
pub const FRONT_END_MID_DC_OBSERVATION_GUARD: Option<ObservationGuardMetadata> = Some(ObservationGuardMetadata {
    code: 65535,
    behavior: ObservationGuardBehavior::Error,
});

#[rustfmt::skip]
static GUARDED_IDENTITY_INPUTS: [u16; 2] = [1, 10];
#[rustfmt::skip]
static GUARDED_IDENTITY_OUTPUTS: [i32; 2] = [1, 10];
/// "guarded\_identity" sparse physical transfer function.
///
/// Source provenance: none declared.
/// Representation: "formula y = x".
/// Generation policy: requested interpolation error <= 1; max_knots = 8; below = error; above = clamp.
/// Domain: 1..=10 "adc\_code"; output: "millivolt" x 1.
/// Knots: 2 (12 bytes array payload).
/// Exhaustive numerical error: requested <= 1, achieved 0.000000 output quanta
/// (conservative metadata bound 0) at input 1.
/// This is table/quantization error against the configured ideal source, not total sensor accuracy.
/// Observation guard: code 65535 with Error behavior.
/// Classification of this code as saturation is declared consumer/device policy, not inferred from the integer value.
#[rustfmt::skip]
pub const GUARDED_IDENTITY: PiecewiseLinearTransfer<2> =
PiecewiseLinearTransfer::new(&GUARDED_IDENTITY_INPUTS, &GUARDED_IDENTITY_OUTPUTS, MonotonicDirection::Increasing)
.with_boundaries(BoundaryBehavior::Error, BoundaryBehavior::Clamp)
.with_observation_guard(65535, ObservationGuardBehavior::Error);
/// Metadata for [`GUARDED_IDENTITY`].
pub const GUARDED_IDENTITY_METADATA: TransferMetadata = TransferMetadata {
    input_unit: "adc_code",
    output_unit: "millivolt",
    output_scale: 1,
    domain_min: 1,
    domain_max: 10,
    range_min: 1,
    range_max: 10,
    direction: MonotonicDirection::Increasing,
    knot_count: 2,
    strictly_monotonic: true,
    flat_segment_count: 0,
    requested_max_error: 1,
    achieved_max_error: 0,
    worst_case_input: 1,
    achieved_max_inverse_code_error: 0,
};
/// Optional observation-code guard for [`GUARDED_IDENTITY`].
///
/// Classification of a code as saturation is declared consumer/device policy,
/// not inferred from the integer value. The runtime getter and this constant agree.
pub const GUARDED_IDENTITY_OBSERVATION_GUARD: Option<ObservationGuardMetadata> = Some(ObservationGuardMetadata {
    code: 65535,
    behavior: ObservationGuardBehavior::Error,
});
