// Auto-generated by ph-curves-gen. Do not edit.

use ph_curves::{BoundaryBehavior, MonotonicDirection, ObservationGuardBehavior, ObservationGuardMetadata, PiecewiseLinearTransfer, TransferMetadata};

#[rustfmt::skip]
static GUARDED_ERROR_INPUTS: [u16; 2] = [1, 10];
#[rustfmt::skip]
static GUARDED_ERROR_OUTPUTS: [i32; 2] = [1, 10];
/// "guarded\_error" sparse physical transfer function.
///
/// Source provenance: none declared.
/// Representation: "formula y = x".
/// Generation policy: requested interpolation error <= 1; max_knots = 8; below = error; above = clamp.
/// Domain: 1..=10 "count"; output: "unit" x 1.
/// Knots: 2 (12 bytes array payload).
/// Exhaustive numerical error: requested <= 1, achieved 0.000000 output quanta
/// (conservative metadata bound 0) at input 1.
/// This is table/quantization error against the configured ideal source, not total sensor accuracy.
/// Observation guard: code 65535 with Error behavior.
/// Classification of this code as saturation is declared consumer/device policy, not inferred from the integer value.
#[rustfmt::skip]
pub const GUARDED_ERROR: PiecewiseLinearTransfer<2> =
PiecewiseLinearTransfer::new(&GUARDED_ERROR_INPUTS, &GUARDED_ERROR_OUTPUTS, MonotonicDirection::Increasing)
.with_boundaries(BoundaryBehavior::Error, BoundaryBehavior::Clamp)
.with_observation_guard(65535, ObservationGuardBehavior::Error);
/// Metadata for [`GUARDED_ERROR`].
pub const GUARDED_ERROR_METADATA: TransferMetadata = TransferMetadata {
    input_unit: "count",
    output_unit: "unit",
    output_scale: 1,
    domain_min: 1,
    domain_max: 10,
    range_min: 1,
    range_max: 10,
    direction: MonotonicDirection::Increasing,
    knot_count: 2,
    strictly_monotonic: true,
    flat_segment_count: 0,
    requested_max_error: 1,
    achieved_max_error: 0,
    worst_case_input: 1,
    achieved_max_inverse_code_error: 0,
};
/// Optional observation-code guard for [`GUARDED_ERROR`].
///
/// Classification of a code as saturation is declared consumer/device policy,
/// not inferred from the integer value. The runtime getter and this constant agree.
pub const GUARDED_ERROR_OBSERVATION_GUARD: Option<ObservationGuardMetadata> = Some(ObservationGuardMetadata {
    code: 65535,
    behavior: ObservationGuardBehavior::Error,
});

#[rustfmt::skip]
static GUARDED_FAMILY_VARIANT_CLAMP_INPUTS: [u16; 2] = [1, 10];
#[rustfmt::skip]
static GUARDED_FAMILY_VARIANT_CLAMP_OUTPUTS: [i32; 2] = [10, 1];
/// "guarded\_family\_variant\_clamp" sparse physical transfer function.
///
/// Source provenance: identity "test fixture".
/// Representation: "formula y = 11 - x".
/// Generation policy: requested interpolation error <= 1; max_knots = 8; below = clamp; above = error.
/// Domain: 1..=10 "count"; output: "unit" x 1.
/// Knots: 2 (12 bytes array payload).
/// Exhaustive numerical error: requested <= 1, achieved 0.000000 output quanta
/// (conservative metadata bound 0) at input 1.
/// This is table/quantization error against the configured ideal source, not total sensor accuracy.
/// Observation guard: code 65535 with Clamp behavior.
/// Classification of this code as saturation is declared consumer/device policy, not inferred from the integer value.
#[rustfmt::skip]
pub const GUARDED_FAMILY_VARIANT_CLAMP: PiecewiseLinearTransfer<2> =
PiecewiseLinearTransfer::new(&GUARDED_FAMILY_VARIANT_CLAMP_INPUTS, &GUARDED_FAMILY_VARIANT_CLAMP_OUTPUTS, MonotonicDirection::Decreasing)
.with_boundaries(BoundaryBehavior::Clamp, BoundaryBehavior::Error)
.with_observation_guard(65535, ObservationGuardBehavior::Clamp);
/// Metadata for [`GUARDED_FAMILY_VARIANT_CLAMP`].
pub const GUARDED_FAMILY_VARIANT_CLAMP_METADATA: TransferMetadata = TransferMetadata {
    input_unit: "count",
    output_unit: "unit",
    output_scale: 1,
    domain_min: 1,
    domain_max: 10,
    range_min: 1,
    range_max: 10,
    direction: MonotonicDirection::Decreasing,
    knot_count: 2,
    strictly_monotonic: true,
    flat_segment_count: 0,
    requested_max_error: 1,
    achieved_max_error: 0,
    worst_case_input: 1,
    achieved_max_inverse_code_error: 0,
};
/// Optional observation-code guard for [`GUARDED_FAMILY_VARIANT_CLAMP`].
///
/// Classification of a code as saturation is declared consumer/device policy,
/// not inferred from the integer value. The runtime getter and this constant agree.
pub const GUARDED_FAMILY_VARIANT_CLAMP_OBSERVATION_GUARD: Option<ObservationGuardMetadata> = Some(ObservationGuardMetadata {
    code: 65535,
    behavior: ObservationGuardBehavior::Clamp,
});
